server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/crsp?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  application:
    name: crsp
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB #1개의 파일의 최대사이즈
      max-request-size: 20MB # 전체 요청의 최대사이즈

  jwt:
    secret: eW91bmdzaWstc3ByaW5nLWJvb3Qtc3RvcmV0YWJsZXJlc2VydmF0aW9uc2VydmljZS1wcm9qZWN0LXR1dG9yaWFsLWp3dC1zZWNyZXQta2V5Cg==
# 아임 포트
IMP_API_KEY: 4627373384371080
imp:
  api:
    secretKey: YDkJUiY0CBOD4lcS2u5yhLF0aanmAMqKhsrNcbJFMSoJaRF2nkGLCukgCmFxrrEP1068NZko93Zck2ml
